remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: WAFIShield
description: A two-layer, fully-extensible Python package for protecting LLM/agent apps against OWASP Top 10 and other evolving LLM vulnerabilities
show_downloads: true
google_analytics:

github:
  is_project_page: true
  repository_url: https://github.com/duestack/wafishield
  repository_name: wafishield
  owner_name: duestack
  owner_url: https://github.com/duestack
